name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f200bf29d43d6e97be690f444c5ea791440563ac7b065c6a7d363bccf654330"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
