name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15f64a0ad7ae815f405c7143efa6aa497601b5b5a83a46bb42a6f9b68b08c165"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
