name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13aab540eac16e81652cd0dd802e72079c985cc264cd4e4df08f380352684965"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
