name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c03972132507c8c43481454ce4f3d1abcd5b9b0c1c898b4daef94c0ff27276"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
