name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729dff8922db893a217d4b8c7deaf88515f417ee0dfd45288bb1ddd6eb64635f"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
