name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ad44e8782651a7056eb3c2cefc561cc823c9c3c9322cf95b6c41e63550c758"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
