name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d3da9c9054df2f0d09b7a88e71a20ef07f423a4b44933a029ea520b5c682244"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
