name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73cf943375df0b7b76a6531d3c69630c324883b25d656d0aa43aee88a552a5ea"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
