name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d227baa24759269e0c7815231b04c68d52b5d2bbc78a8070c4e1f07950a713b"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
