name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb0184864d2b70cc4b843e6f6b3fe58340fbad1ec58adc00ac23e57a805fe765"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
