name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4a8cfc1272e8f51dd4ba8fd275af94698852149bab3e3c7ad75c088073da1ea"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
