name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dff5af92b6233d3fe6f7275a35889f19dcf8f28a0f69add8f12ea8bcf1cf310b"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
