name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "505c977fb3a06d57eb0853dfd0d89db4c4a1545b06c5d477c81c02289d6c5243"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
