name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07adaaac498d5dd96168d7fbbb3012355edf941728de43fd9f0ba58f993a4a66"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
