name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48bd5f375a5b07107d038322fce0b23248543052676efcb53dd0f8fde2881751"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
