name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a17eb433acf11d9166c17dc4b774a6c5d8f913b21428b48776c5793747c4f0c8"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
