name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "221032306251bb7affeddbbbfbac9925e0232d3dc3e0ba6a8da4c7ff14ea0e26"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
