name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c78edcd10ccd12fb9c71bb22e5c237ba160806b256daa39d6b335ae0d08c1360"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
