name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3a68ecf0f6fb95a4f706dc68da9c3903a9470d29d0d1c7bffaa1e8ac01da4f"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
