name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19f9cd78be4dbb1c57c26e1788730deef8d394b868d58c61c4de548d41d27c38"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
