name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0b8e748ce4445b90080af72d571ada60c0aed0422f748f1981553e7091fabe5"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
