name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa2ac5ff1eac80ea9066c0df120775c6cc7ec0fb15ccc117d092d5037a163a20"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
