name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bc832585b564e086bc47a38b1946ae21090ae84c1064fdd69f70095cfc98f75"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
