name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258855dafd84683680b495efeff7eebcb7490b778cc8d76eb49744b9bec41bcf"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
