name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b142fa34bf57366facd14ccf0822c2289835a2df08206970662bc15f130d64a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
