name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f03ed096ed0859ce434ac684b7601a9336f8124e7eb9fdd69cb4e29a2ee00b0f"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
