name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a06fef85a4b6a2fe6002f5f0ef09d7dd749ef5384865722e311a0673d37faeb"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
