name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a56ad202762a6808d1caee0e87a4ebfc8f32d3e425196422ee9d238bafa9ebf"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
