name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fd5b224191465943de466cf57bb2ce77ec26a3ee6d53e09aa64d9ee497ef555"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
