name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9e1992ac7a306be78858c085019923798ed39ad5882c5f67696c127df61824d"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
