name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0fd7c9c46e0f43aa40c67fe718bce1143796fee56f2740bab990921d4b1f810"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
