name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34432b1096bce0361911cfae9a969e3099a9d0ae65a9d9032d024b40e4f8ef34"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
