name = "Nick's Modern Classic"
author = "Nick Bernhoft"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b85e2f6d053dfd77f96b33e2384ab4107fa1ed857cf7ca44698276cc60816395"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
